### ISSUE TITLE
Integrating tfrs with tfx

### ISSUE THREAD

**Issue by yrianderreumaux** [tensorflow/recommenders-addons#162]
I am trying to integrate a tfrs model with [tfx](https://www.tensorflow.org/tfx), and I see that it's in the scope of recommender-addons ("End-to-end pipeline: how to train continuously, e.g. integrate with platforms like TFX"). However, I have not been able to find any docs or example pipelines to accomplish this. I am hoping to implement best practices, and in particular looking for help integrating the model with [tft](https://www.tensorflow.org/tfx/transform/get_started). 

Any help would be much appreciated!

**Comment by yrianderreumaux** [comment]
Checking in again on this request in case there are any updates.

**Comment by Mr-Nineteen** [comment]
we practice plan:  **TFRA on TensorFlow + Estimator + TFServing(TRT)**，other components have not been tried.

1. code demo: https://github.com/tensorflow/recommenders-addons/tree/master/demo/dynamic_embedding/movielens-100k-estimator
2. Compatibility with Tensorflow Serving: https://github.com/tensorflow/recommenders-addons/blob/master/README.md#compatibility-with-tensorflow-serving
3. If TFServing uses GPU, TRT uses tf.experimental.tensorrt.Converter(). At the same time, mlp is calculated on the GPU, and the embedding lookup is on the CPU, so that the performance is optimal.

**Comment by yrianderreumaux** [comment]
Thanks for this info @Mr-Nineteen!

**Comment by yrianderreumaux** [comment]
Closing until there are further updates specific to TFX
