### ISSUE TITLE
keras dependency error~.  

### ISSUE THREAD

**Issue by calliwen** [tensorflow/recommenders-addons#237]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu20.04
- TensorFlow version and how it was installed (source or binary): binary, tf-2.5.1
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): 0.4.0
- Python version: 3.8
- Is GPU used? (yes/no):yes

**Describe the bug**

from collection, you could manually add it to the collection by tf.compat.v1.add_to_collections (names, var) instead.
2022-04-06 07:36:54.954465: I tensorflow/stream_executor/platform/default/do_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last) :
File "movielens-100k-estimator.py", line 8, in ‹modules
import tensorflow_recommenders_addons as tfra
File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/_init_-py",line29,in<module>
from tensorflow recommenders addons import dynamic embedding
File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/_
init
_.py", line 93, in
<module>
from tensorflow_recommenders_addons.dynamic_embedding.python.ops.tf_patch import T
File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py",line38,in<module>
import keras as K
File "/usr/local/lib/python3.8/dist-packages/keras/__init_-py",line25,in<module>
from keras import models
File "/usr/local/lib/python3.8/dist-packages/keras/models.py", line 19, in «modules
from keras import backend
File
"/usr/local/lib/python3.8/dist-packages/keras/backend.py", line 301, in «modules
tf.
AttributeError: module 'tensorflow.compat.v2._
internal register clear session function(clear, session' attribute ^ register clear session function

It seems that "import keras as K" is error.

**Code to reproduce the issue**
[demo](https://github.com/tensorflow/recommenders-addons/tree/master/demo)/[dynamic_embedding](https://github.com/tensorflow/recommenders-addons/tree/master/demo/dynamic_embedding)/movielens-100k-sync-estimator-with-horovod/

run the demo.  
bash train.sh

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by calliwen** [comment]
I change my env to :

**Comment by calliwen** [comment]
:

**Comment by calliwen** [comment]
I change my env:

**Comment by calliwen** [comment]
I change my env to follow:
python[3.8 --> 3.7]
horovod[0.24.2 --> 0.23.0]
keras[0.28.0/-nightly-2.5.0  --> 2.3.0 ]

It works on cpu version.

I give the Dockerfile content as follow:  [refer to : [horovod-dockerfile]](https://github.com/horovod/horovod/blob/v0.23.0/docker/horovod/Dockerfile)

ARG CUDA_DOCKER_VERSION=11.2.2-devel-ubuntu18.04
FROM nvidia/cuda:${CUDA_DOCKER_VERSION}

# Arguments for the build. CUDA_DOCKER_VERSION needs to be repeated because
# the first usage only applies to the FROM tag.
# TensorFlow version is tightly coupled to CUDA and cuDNN so it should be selected carefully
ARG CUDA_DOCKER_VERSION=11.2.2-devel-ubuntu18.04
ARG TENSORFLOW_VERSION=2.5.0
ARG PYTORCH_VERSION=1.8.1+cu111
ARG PYTORCH_LIGHTNING_VERSION=1.2.9
ARG TORCHVISION_VERSION=0.9.1+cu111
ARG CUDNN_VERSION=8.1.1.33-1+cuda11.2
ARG NCCL_VERSION=2.8.4-1+cuda11.2
ARG MXNET_VERSION=1.8.0.post0

ARG PYSPARK_PACKAGE=pyspark==3.1.1
ARG SPARK_PACKAGE=spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz

# Python 3.7 is supported by Ubuntu Bionic out of the box
ARG PYTHON_VERSION=3.7

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        g++-7 \
        git \
        curl \
        vim \
        wget \
		unzip \
		autoconf \
		automake \
		libtool \
        ca-certificates \
        libcudnn8=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-distutils \
        librdmacm1 \
        libibverbs1 \
        ibverbs-providers \
        openjdk-8-jdk-headless \
        openssh-client \
        openssh-server \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Open MPI
# RUN wget --progress=dot:mega -O /tmp/openmpi-3.0.0-bin.tar.gz https://github.com/horovod/horovod/files/1596799/openmpi-3.0.0-bin.tar.gz && \
#     cd /usr/local && \
#     tar -zxf /tmp/openmpi-3.0.0-bin.tar.gz && \
#     ldconfig && \
#     mpirun --version

# Install Open MPI
# https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz
RUN wget --progress=dot:mega -O /tmp/openmpi-4.1.2.tar.gz https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz && \
    cd /usr/local && \
    tar -zxf /tmp/openmpi-4.1.2.tar.gz && \
	cd openmpi-4.1.2/ && \
	./configure --prefix=/usr/local/openmpi-4.1.2 && \
	make -j 32 && make all install && \
	ldconfig && \
	/usr/local/openmpi-4.1.2/bin/mpirun --version && \
	export PATH=$PATH:/usr/local/openmpi-4.1.2/bin && \
	export LD_LIBRARY_PATH=/usr/local/openmpi-4.1.2/lib:$LD_LIBRARY_PATH && \
	mpirun --version

RUN wget --progress=dot:mega -O /tmp/protobuf-3.9.2.tar.gz https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.9.2.tar.gz && \
	cd /usr/local && \
	tar -zxf /tmp/protobuf-3.9.2.tar.gz && \
	cd protobuf-3.9.2/ && \
	./autogen.sh && ./configure --prefix=/usr/local/protobuf/3_9_0 && \
	make -j 32 && make install && \
	ldconfig


# Allow OpenSSH to talk to containers without asking for confirmation
RUN mkdir -p /var/run/sshd
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

RUN ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# # Install PyTorch, TensorFlow, Keras and MXNet
# RUN pip install --no-cache-dir \
#     torch==${PYTORCH_VERSION} \
#     torchvision==${TORCHVISION_VERSION} \
#     -f https://download.pytorch.org/whl/${PYTORCH_VERSION/*+/}/torch_stable.html
# RUN pip install --no-cache-dir pytorch_lightning==${PYTORCH_LIGHTNING_VERSION}


RUN pip install --no-cache-dir \
		Pillow \
		h5py \
		typing \
		packaging \
		matplotlib \
		mock \
		numpy \
		scipy \
		sklearn \
		pandas \
		future \
		portpicker \
		enum34 \
		six \
		wheel \
		setuptools \
		quick-queue \
		pulsar-client \
		ipython \
		keras_preprocessing \
		keras_applications \
		flatbuffers \
		tensorflow_gpu==2.5.1 \
		tensorflow-recommenders-addons-gpu==0.4.0 \
		tensorflow-datasets \
	&& pip uninstall -y keras keras-nightly \
	&& pip install --no-cache-dir keras==2.3.0 

# RUN pip install --no-cache-dir mxnet-cu112==${MXNET_VERSION}

# # Install Spark stand-alone cluster.
# RUN wget --progress=dot:giga "https://www.apache.org/dyn/closer.lua/spark/${SPARK_PACKAGE}?action=download" -O - | tar -xzC /tmp; \
#     archive=$(basename "${SPARK_PACKAGE}") bash -c "mv -v /tmp/\${archive/%.tgz/} /spark"

# # Install PySpark.
# RUN pip install --no-cache-dir ${PYSPARK_PACKAGE}


# # Install Horovod, temporarily using CUDA stubs
# WORKDIR /horovod
# COPY . .
# RUN python setup.py sdist && \
#     ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
#     bash -c "HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install --no-cache-dir -v $(ls /horovod/dist/horovod-*.tar.gz)[spark,ray]" && \
#     horovodrun --check-build && \
#     ldconfig
RUN HOROVOD_GPU_OPERATIONS=NCCL pip install --no-cache-dir horovod==0.23.0


# # Check all frameworks are working correctly. Use CUDA stubs to ensure CUDA libs can be found correctly
# # when running on CPU machine
# WORKDIR "/horovod/examples"
# RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
#     python -c "import horovod.tensorflow as hvd; hvd.init()" && \
#     python -c "import horovod.torch as hvd; hvd.init()" && \
#     python -c "import horovod.mxnet as hvd; hvd.init()" && \
#     ldconfig

WORKDIR "/horovod/examples"
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    python -c "import horovod.tensorflow as hvd; hvd.init()" && \
    ldconfig

WORKDIR "/data/"

**Comment by rhdong** [comment]
Hi @calliwen , thank you for your feedback, I'll check it ASAP.

**Comment by NeesonGao** [comment]
> 
Hello, rhdong, This account is my new account. I update my new environment as follow(refers to [horovod Dockerfile](https://github.com/horovod/horovod/blob/v0.23.0/docker/horovod/Dockerfile) ):
【Needs to git clone, git checkout v0.23.0, git submodule init & git submodule update; And then to build docker images.】


ARG CUDA_DOCKER_VERSION=11.2.2-devel-ubuntu18.04
FROM nvidia/cuda:${CUDA_DOCKER_VERSION}

# Arguments for the build. CUDA_DOCKER_VERSION needs to be repeated because
# the first usage only applies to the FROM tag.
# TensorFlow version is tightly coupled to CUDA and cuDNN so it should be selected carefully
ARG CUDA_DOCKER_VERSION=11.2.2-devel-ubuntu18.04
ARG TENSORFLOW_VERSION=2.5.0
ARG PYTORCH_VERSION=1.8.1+cu111
ARG PYTORCH_LIGHTNING_VERSION=1.2.9
ARG TORCHVISION_VERSION=0.9.1+cu111
ARG CUDNN_VERSION=8.1.1.33-1+cuda11.2
ARG NCCL_VERSION=2.8.4-1+cuda11.2
ARG MXNET_VERSION=1.8.0.post0

ARG PYSPARK_PACKAGE=pyspark==3.1.1
ARG SPARK_PACKAGE=spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz

# Python 3.7 is supported by Ubuntu Bionic out of the box
ARG PYTHON_VERSION=3.7

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        g++-7 \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        libcudnn8=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev \
        python${PYTHON_VERSION}-distutils \
        librdmacm1 \
        libibverbs1 \
        ibverbs-providers \
        openjdk-8-jdk-headless \
        openssh-client \
        openssh-server \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Open MPI
RUN wget --progress=dot:mega -O /tmp/openmpi-3.0.0-bin.tar.gz https://github.com/horovod/horovod/files/1596799/openmpi-3.0.0-bin.tar.gz && \
    cd /usr/local && \
    tar -zxf /tmp/openmpi-3.0.0-bin.tar.gz && \
    ldconfig && \
    mpirun --version

# # Install Open MPI
# # https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz
# RUN wget --progress=dot:mega -O /tmp/openmpi-4.1.2.tar.gz https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz && \
#     cd /usr/local && \
#     tar -zxf /tmp/openmpi-4.1.2.tar.gz && \
# 	cd openmpi-4.1.2/ && \
# 	./configure --prefix=/usr/local/ && \
# 	make -j 32 && make all install && \
# 	ldconfig

# ENV PATH=/usr/local/bin:$PATH
# ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH



# Allow OpenSSH to talk to containers without asking for confirmation
RUN mkdir -p /var/run/sshd
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

RUN ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# Install PyTorch, TensorFlow, Keras and MXNet
RUN pip install --no-cache-dir \
    torch==${PYTORCH_VERSION} \
    torchvision==${TORCHVISION_VERSION} \
    -f https://download.pytorch.org/whl/${PYTORCH_VERSION/*+/}/torch_stable.html
RUN pip install --no-cache-dir pytorch_lightning==${PYTORCH_LIGHTNING_VERSION}

# RUN pip install --no-cache-dir future typing packaging
# RUN pip install --no-cache-dir \
#     tensorflow==${TENSORFLOW_VERSION} \
#     keras \
#     h5py


RUN pip install --no-cache-dir \
		Pillow \
		h5py \
		typing \
		packaging \
		matplotlib \
		mock \
		numpy \
		scipy \
		sklearn \
		pandas \
		future \
		portpicker \
		enum34 \
		six \
		wheel \
		setuptools \
		quick-queue \
		pulsar-client \
		ipython \
		keras_preprocessing \
		keras_applications \
		flatbuffers \
		tensorflow_gpu==2.5.1 \
		tensorflow-recommenders-addons-gpu==0.4.0 \
		tensorflow-datasets \
	&& pip uninstall -y keras keras-nightly \
	&& pip install --no-cache-dir keras==2.3.0 


RUN pip install --no-cache-dir mxnet-cu112==${MXNET_VERSION}

# Install Spark stand-alone cluster.
RUN wget --progress=dot:giga "https://www.apache.org/dyn/closer.lua/spark/${SPARK_PACKAGE}?action=download" -O - | tar -xzC /tmp; \
    archive=$(basename "${SPARK_PACKAGE}") bash -c "mv -v /tmp/\${archive/%.tgz/} /spark"

# Install PySpark.
RUN pip install --no-cache-dir ${PYSPARK_PACKAGE}

# Install Horovod, temporarily using CUDA stubs
WORKDIR /horovod
COPY . .
RUN python setup.py sdist && \
    ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    bash -c "HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install --no-cache-dir -v $(ls /horovod/dist/horovod-*.tar.gz)[spark,ray]" && \
    horovodrun --check-build && \
    ldconfig

# Check all frameworks are working correctly. Use CUDA stubs to ensure CUDA libs can be found correctly
# when running on CPU machine
WORKDIR "/horovod/examples"
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    python -c "import horovod.tensorflow as hvd; hvd.init()" && \
    python -c "import horovod.torch as hvd; hvd.init()" && \
    python -c "import horovod.mxnet as hvd; hvd.init()" && \
    ldconfig

WORKDIR /data

**Comment by rhdong** [comment]
Hi @calliwen @NeesonGao , I confirm this issue should be resolved in the latest release, pls check it and feel free to reopen it if needed. https://github.com/tensorflow/recommenders-addons/releases/tag/v0.5.0, thank you for your feedback!
