### ISSUE TITLE
Waiting for model to be ready. Ready_for_local_init_op: Variables not initialized: beta1_power, beta2_power, ready: None

### ISSUE THREAD

**Issue by Mr-Nineteen** [tensorflow/recommenders-addons#38]
During training, the optimizer is **tf.compat.v1.train.AdamOptimizer**, and it appears: "**Waiting for model to be ready. Ready_for_local_init_op: Variables not initialized: beta1_power, beta2_power, ready: None**", the scene is:

1. variable_scope + partitioner
2. Remove BN

**Comment by rhdong** [comment]
The `TrainableWrapper` still not works well with variable_scope + partitioner , We will spend long time to push a PR to TensorFlow core to resolve this problem and as an equivalent alternative, you can use partitioner in `tf.get_variable` directly.

**Comment by rhdong** [comment]
Adam's _create_slots function is coordinated according to the variable with the lowest name in var_list, plz refer to [here](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/python/training/adam.py#L130). When BN is turned off(maybe triggered by special conditions), the dynamic embedding TrainableWrapper in var_list will be brought to the front . When `colocate_with` TrainableWrapper's the device that is not `/job:ps`, but `/job:worker`, resulting in The variable is not initialized. For we can change the adam._create_slots in TF and we also had to keep the `TrainbleWrapper` on `/job:worker` local. Then the way to avoid this issue is changing the first letter of the name of the `tfra.embedding_lookup(name='z-xxxx')` to ‘z’ so that it will be queued to the back.
