### ISSUE TITLE
tfra already support tf 1.15.2

### ISSUE THREAD

**Issue by ideafold** [tensorflow/recommenders-addons#97]
https://github.com/tensorflow/recommenders-addons/blob/9257222cda9115148e840958e0bff4c147bd53b7/tensorflow_recommenders_addons/version.py#L20

min tf version updated to 1.15.2??

**Comment by rhdong** [comment]
This TF_VERSION will change according to TF installed. in fact
MIN_TF_VERSION is  equal to MAX_TF_VERSION in one compile.

ideafold ***@***.***> 于2021年6月4日周五 下午4:53写道：

**Comment by amznero** [comment]
It would be better to set the environment variable `TF_VERSION=1.15.2` when the user installing tfra from source(for tf 1.15.2). Otherwise, the `version.py` will not update MIN_TF_VERSION. Eventually, when the user executes `pip install artifacts/tensorflow_recommenders_addons-*.whl`, tensorflow will be updated to 2.4.1 due to the wheel requires TF MIN_TF_VERSION=2.4.1.

```
...

# This script links project with TensorFlow dependency
TF_VERSION="1.15.2" \
python configure.py

...

```

**Comment by rhdong** [comment]
> It would be better to set the environment variable `TF_VERSION=1.15.2` when the user installing tfra from source(for tf 1.15.2). Otherwise, the `version.py` will not update MIN_TF_VERSION. Eventually, when the user executes `pip install artifacts/tensorflow_recommenders_addons-*.whl`, tensorflow will be updated to 2.4.1 due to the wheel requires TF MIN_TF_VERSION=2.4.1.
> 
> ```
> ...
> 
> # This script links project with TensorFlow dependency
> export TF_VERSION="1.15.2"
> python configure.py
> 
> ...
> ```

Hi @amznero , thank you for your feedback, I believe your advice is good. Now compiling TFRA always requires a TF installation in environment that can avoid compiling the whole TF,  So `export TF_VERSION` may be ok , but we have to consider special case that `TF_VERSION` is not match real installation of TF. I tend to keep the status quo, because there should be only one source for get required TF version. Do you think it's ok？

**Comment by rhdong** [comment]
> It would be better to set the environment variable `TF_VERSION=1.15.2` when the user installing tfra from source(for tf 1.15.2). Otherwise, the `version.py` will not update MIN_TF_VERSION. Eventually, when the user executes `pip install artifacts/tensorflow_recommenders_addons-*.whl`, tensorflow will be updated to 2.4.1 due to the wheel requires TF MIN_TF_VERSION=2.4.1.
> 
> ```
> ...
> 
> # This script links project with TensorFlow dependency
> export TF_VERSION="1.15.2"
> python configure.py
> 
> ...
> ```

Hi @amznero , I'm Sorry, you're right, I will change the readme.

**Comment by rhdong** [comment]
https://github.com/tensorflow/recommenders-addons/pull/106
